"""Contenido legal de la Política de Privacidad (Telvoice.cl).

Editar SECTIONS y regenerar la página con:

    python3 scripts/build-privacidad-page.py
"""

SECTIONS = [
    ("1. Introducción", [
        ("p", "En Telvoice.cl valoramos la privacidad y la protección de los datos personales de nuestros usuarios, clientes, representantes de empresas, contactos comerciales y destinatarios relacionados con los servicios de mensajería SMS."),
        ("p", "La presente Política de Privacidad explica cómo Telefoniachile Ltda, a través de Telvoice.cl, recopila, utiliza, almacena, protege y, cuando corresponde, comparte datos personales en el contexto de sus servicios de venta de bolsas SMS, gestión de campañas, acceso API, soporte, facturación y operación de mensajería empresarial."),
        ("p", "Al acceder al sitio web, registrarse, comprar servicios, solicitar información, utilizar la plataforma, contactar a Telvoice.cl o integrar servicios mediante API, el usuario declara haber leído y comprendido esta Política de Privacidad."),
    ]),
    ("2. Alcance de esta política", [
        ("p", "Esta Política de Privacidad se aplica a:"),
        ("ul", [
            "Usuarios que navegan en telvoice.cl.",
            "Personas que completan formularios de contacto o solicitud de cotización.",
            "Clientes que compran bolsas de SMS.",
            "Empresas que solicitan acceso API.",
            "Usuarios registrados en la plataforma.",
            "Representantes comerciales, administrativos o técnicos de clientes.",
            "Personas que se comunican con Telvoice.cl por correo, WhatsApp, teléfono u otros canales.",
            "Datos tratados para ejecutar campañas SMS, cuando Telvoice.cl actúe como proveedor tecnológico u operador del servicio.",
        ]),
        ("p", "Esta política no regula sitios web, plataformas, pasarelas de pago, servicios de terceros o enlaces externos que no sean controlados directamente por Telvoice.cl."),
    ]),
    ("3. Responsable del tratamiento de datos", [
        ("p", "Para efectos de esta Política de Privacidad, el responsable del tratamiento de los datos personales recopilados directamente a través de Telvoice.cl es:"),
        ("contact", [
            ("Titular", "Telefoniachile Ltda", None),
            ("RUT", "76.287.242-0", None),
            ("Domicilio", "Av Caupolicán 222, Temuco, Chile", None),
            ("Correo de contacto", "contacto@telvoice.cl", "mailto:contacto@telvoice.cl"),
            ("Correo legal / cumplimiento", "legal@telvoice.cl", "mailto:legal@telvoice.cl"),
        ]),
        ("p", "Respecto de los datos de destinatarios cargados, enviados o tratados por clientes para campañas SMS, el cliente será responsable de contar con autorización, consentimiento o base legal suficiente para utilizar dichos datos. En esos casos, Telvoice.cl podrá actuar como proveedor tecnológico, operador o encargado del tratamiento, según la naturaleza del servicio contratado."),
    ]),
    ("4. Datos personales que podemos recopilar", [
        ("p", "Telvoice.cl podrá recopilar datos personales necesarios para operar el sitio, prestar los servicios, gestionar compras, entregar soporte, procesar pagos, administrar cuentas, prevenir fraude y cumplir obligaciones legales."),
        ("p", "Los datos recopilados pueden incluir:"),
        ("h3", "4.1. Datos de identificación"),
        ("ul", [
            "Nombre y apellido.",
            "Nombre de empresa o razón social.",
            "RUT o identificación tributaria.",
            "Cargo o rol dentro de la empresa.",
            "Datos del representante legal o comercial, cuando corresponda.",
        ]),
        ("h3", "4.2. Datos de contacto"),
        ("ul", [
            "Correo electrónico.",
            "Número de teléfono.",
            "Dirección comercial.",
            "País, región o ciudad.",
            "Canal de contacto preferido.",
        ]),
        ("h3", "4.3. Datos de cuenta y acceso"),
        ("ul", [
            "Usuario de plataforma.",
            "Credenciales de acceso cifradas o protegidas.",
            "Tokens o claves API.",
            "Historial de inicio de sesión.",
            "Dirección IP.",
            "Registros de seguridad y actividad.",
        ]),
        ("h3", "4.4. Datos comerciales y de facturación"),
        ("ul", [
            "Información de compra.",
            "Bolsas SMS adquiridas.",
            "Historial de pagos.",
            "Monto, moneda y fecha de transacción.",
            "Datos necesarios para emitir factura, boleta o comprobante.",
            "Información asociada a pasarelas de pago, cuando corresponda.",
        ]),
        ("p", "Telvoice.cl no almacena directamente los datos completos de tarjetas bancarias u otros medios de pago, salvo la información mínima necesaria para registrar la transacción, validar la compra o cumplir obligaciones contables y legales."),
        ("h3", "4.5. Datos técnicos y de uso"),
        ("ul", [
            "Dirección IP.",
            "Tipo de navegador.",
            "Dispositivo utilizado.",
            "Sistema operativo.",
            "Páginas visitadas.",
            "Fecha y hora de acceso.",
            "Interacciones dentro del sitio.",
            "Información de rendimiento, errores o uso de la plataforma.",
            "Cookies, identificadores técnicos o tecnologías similares, cuando sean utilizadas.",
        ]),
        ("h3", "4.6. Datos asociados a campañas SMS"),
        ("p", "Cuando el usuario utiliza Telvoice.cl para enviar campañas SMS, se podrán tratar datos operativos necesarios para ejecutar el servicio, tales como:"),
        ("ul", [
            "Números telefónicos de destinatarios.",
            "Contenido de los mensajes.",
            "Fecha y hora de envío.",
            "Estado técnico del mensaje.",
            "Reportes de entrega, rechazo, expiración o falla, cuando estén disponibles.",
            "Identificador de campaña.",
            "Información técnica de ruta, operador o país de destino.",
            "Registros necesarios para trazabilidad, soporte y cumplimiento.",
        ]),
        ("p", "El usuario declara que los números telefónicos, bases de datos y contenidos utilizados en campañas SMS fueron obtenidos de forma lícita y cuentan con autorización, consentimiento o base legal suficiente."),
    ]),
    ("5. Datos que no solicitamos de forma intencional", [
        ("p", "Telvoice.cl no solicita de forma intencional datos personales sensibles, tales como información de salud, religión, orientación política, afiliación sindical, vida sexual, origen racial o étnico, antecedentes biométricos u otros datos especialmente protegidos, salvo que sean estrictamente necesarios por una obligación legal o por una situación excepcional debidamente justificada."),
        ("p", "El usuario no debe cargar, enviar ni incluir datos sensibles en campañas SMS, formularios, mensajes o integraciones, salvo que cuente con autorización legal suficiente y haya tomado las medidas de seguridad correspondientes."),
    ]),
    ("6. Finalidades del tratamiento", [
        ("p", "Telvoice.cl podrá tratar datos personales para las siguientes finalidades:"),
        ("h3", "6.1. Prestación del servicio"),
        ("ul", [
            "Crear y administrar cuentas de usuario.",
            "Procesar compras de bolsas SMS.",
            "Habilitar saldo SMS.",
            "Ejecutar campañas.",
            "Permitir acceso a plataforma o API.",
            "Gestionar reportes y estados de envío.",
            "Entregar soporte comercial y técnico.",
            "Mantener la continuidad operativa del servicio.",
        ]),
        ("h3", "6.2. Gestión comercial"),
        ("ul", [
            "Responder consultas.",
            "Enviar cotizaciones.",
            "Contactar prospectos o clientes.",
            "Informar características del servicio.",
            "Gestionar solicitudes de acceso API.",
            "Enviar comunicaciones relacionadas con productos o servicios de Telvoice.cl.",
            "Realizar seguimiento comercial a solicitudes recibidas.",
        ]),
        ("h3", "6.3. Facturación y administración"),
        ("ul", [
            "Procesar pagos.",
            "Emitir boletas, facturas o comprobantes.",
            "Mantener registros contables.",
            "Gestionar órdenes de compra.",
            "Verificar transacciones.",
            "Administrar saldos, consumos y compras.",
        ]),
        ("h3", "6.4. Seguridad y prevención de fraude"),
        ("ul", [
            "Verificar identidad de usuarios.",
            "Detectar accesos no autorizados.",
            "Prevenir fraude, spam, phishing, smishing o abuso de la plataforma.",
            "Proteger credenciales, tokens y claves API.",
            "Monitorear actividad inusual.",
            "Investigar incidentes de seguridad.",
            "Proteger la reputación de rutas, sistemas y servicios.",
        ]),
        ("h3", "6.5. Cumplimiento normativo"),
        ("ul", [
            "Cumplir obligaciones legales, tributarias, regulatorias o contractuales.",
            "Responder requerimientos de autoridades competentes.",
            "Mantener registros necesarios para auditoría, trazabilidad o investigación.",
            "Gestionar solicitudes de derechos de titulares.",
            "Aplicar políticas de uso permitido y prohibido.",
        ]),
        ("h3", "6.6. Mejora del sitio y del servicio"),
        ("ul", [
            "Analizar uso del sitio.",
            "Mejorar la experiencia de usuario.",
            "Optimizar contenidos, navegación y diseño.",
            "Corregir errores técnicos.",
            "Medir rendimiento de campañas, formularios o páginas.",
            "Desarrollar nuevas funcionalidades.",
        ]),
    ]),
    ("7. Base legal o legitimación del tratamiento", [
        ("p", "Telvoice.cl tratará datos personales cuando exista una base que lo permita, incluyendo:"),
        ("ul", [
            "Consentimiento del titular.",
            "Ejecución de un contrato o prestación de un servicio solicitado.",
            "Cumplimiento de obligaciones legales.",
            "Interés legítimo en operar, proteger, mejorar y administrar el servicio.",
            "Gestión de solicitudes precontractuales o comerciales.",
            "Prevención de fraude, abuso o uso indebido.",
            "Ejercicio o defensa de derechos.",
        ]),
        ("p", "Respecto de los datos de destinatarios utilizados en campañas SMS, el cliente será responsable de contar con la autorización, consentimiento o base legal correspondiente para contactar a dichas personas."),
    ]),
    ("8. Tratamiento de datos de destinatarios de campañas SMS", [
        ("p", "Cuando un cliente utiliza Telvoice.cl para enviar campañas SMS, Telvoice.cl podrá procesar números telefónicos, contenido de mensajes y datos técnicos necesarios para ejecutar el envío."),
        ("p", "En este contexto:"),
        ("ul", [
            "El cliente es responsable del origen, legalidad y autorización de su base de datos.",
            "El cliente debe respetar solicitudes de baja, oposición, exclusión o no contacto.",
            "El cliente debe asegurarse de que sus mensajes sean lícitos, veraces y no engañosos.",
            "El cliente no debe utilizar Telvoice.cl para spam, fraude, smishing, suplantación de identidad o comunicaciones no autorizadas.",
            "Telvoice.cl podrá suspender campañas o cuentas si detecta uso indebido, riesgo legal, reclamos, contenido prohibido o afectación de la operación.",
        ]),
        ("p", "Telvoice.cl no vende, arrienda ni comercializa bases de datos de destinatarios cargadas o utilizadas por sus clientes."),
    ]),
    ("9. Comunicaciones comerciales", [
        ("p", "Telvoice.cl podrá enviar comunicaciones comerciales, informativas o de servicio a usuarios, clientes o prospectos que hayan entregado sus datos de contacto, solicitado información, contratado servicios o mantenido una relación comercial con la empresa."),
        ("p", "Estas comunicaciones pueden incluir:"),
        ("ul", [
            "Información sobre servicios SMS.",
            "Confirmaciones de compra.",
            "Avisos operativos.",
            "Cambios en condiciones del servicio.",
            "Información de soporte.",
            "Novedades comerciales.",
            "Recordatorios relacionados con cuenta, saldo o uso del servicio.",
        ]),
        ("p", "El usuario podrá solicitar dejar de recibir comunicaciones comerciales escribiendo a contacto@telvoice.cl o legal@telvoice.cl, sin perjuicio de que Telvoice.cl pueda seguir enviando comunicaciones estrictamente necesarias para la prestación del servicio, seguridad, facturación o cumplimiento legal."),
    ]),
    ("10. Uso de cookies y tecnologías similares", [
        ("p", "Telvoice.cl podrá utilizar cookies, píxeles, etiquetas, almacenamiento local u otras tecnologías similares para:"),
        ("ul", [
            "Recordar preferencias de navegación.",
            "Mantener sesiones activas.",
            "Mejorar la experiencia de usuario.",
            "Analizar tráfico del sitio.",
            "Medir rendimiento de campañas.",
            "Detectar errores técnicos.",
            "Proteger la seguridad del sitio.",
            "Evaluar el funcionamiento de formularios y páginas.",
        ]),
        ("p", "El usuario puede configurar su navegador para bloquear, eliminar o limitar el uso de cookies. Sin embargo, algunas funcionalidades del sitio o de la plataforma podrían verse afectadas."),
        ("p", "Si Telvoice.cl utiliza herramientas de terceros como analítica web, publicidad, CRM, chat, formularios, pasarelas de pago u otros servicios similares, dichas herramientas podrán tratar ciertos datos conforme a sus propias políticas de privacidad."),
    ]),
    ("11. Proveedores y terceros", [
        ("p", "Para operar sus servicios, Telvoice.cl podrá compartir datos personales o permitir acceso limitado a proveedores necesarios para la prestación del servicio, tales como:"),
        ("ul", [
            "Proveedores de hosting o infraestructura.",
            "Proveedores de plataforma SMS.",
            "Agregadores, carriers u operadores relacionados con la entrega de mensajes.",
            "Pasarelas de pago.",
            "Proveedores de facturación o contabilidad.",
            "Herramientas de soporte, CRM o atención al cliente.",
            "Servicios de analítica web.",
            "Proveedores de seguridad informática.",
            "Asesores legales, contables o tributarios.",
            "Autoridades competentes, cuando exista obligación legal.",
        ]),
        ("p", "Telvoice.cl procurará que dichos terceros accedan únicamente a los datos necesarios para cumplir sus funciones y adopten medidas razonables de confidencialidad y seguridad."),
    ]),
    ("12. Transferencias internacionales", [
        ("p", "Algunos proveedores tecnológicos, plataformas de infraestructura, servicios de mensajería, pasarelas de pago, herramientas de analítica o sistemas de soporte podrían encontrarse ubicados fuera de Chile o procesar datos en servidores internacionales."),
        ("p", "Al utilizar Telvoice.cl, el usuario entiende que sus datos podrán ser tratados o almacenados en otros países cuando ello sea necesario para prestar el servicio, operar la plataforma, procesar pagos, entregar soporte o cumplir fines legítimos del servicio."),
        ("p", "Telvoice.cl procurará adoptar medidas razonables para proteger los datos personales en dichas transferencias, conforme a la normativa aplicable y a estándares adecuados de seguridad."),
    ]),
    ("13. Conservación de los datos", [
        ("p", "Telvoice.cl conservará los datos personales durante el tiempo necesario para cumplir las finalidades descritas en esta Política de Privacidad, prestar los servicios contratados, mantener registros comerciales, cumplir obligaciones legales, resolver disputas, prevenir fraude y atender eventuales responsabilidades."),
        ("p", "Los plazos de conservación pueden variar según el tipo de dato:"),
        ("ul", [
            "Datos de cuenta: mientras la cuenta esté activa o sea necesario conservarlos.",
            "Datos de compra y facturación: durante el plazo exigido por la normativa tributaria y contable.",
            "Registros técnicos y de seguridad: durante el tiempo necesario para protección, auditoría y prevención de incidentes.",
            "Datos de campañas SMS: durante el tiempo necesario para ejecutar el servicio, entregar reportes, resolver reclamos, cumplir obligaciones y mantener trazabilidad operativa.",
            "Datos comerciales: mientras exista relación comercial, solicitud pendiente, consentimiento vigente o interés legítimo aplicable.",
        ]),
        ("p", "Cuando los datos ya no sean necesarios, Telvoice.cl podrá eliminarlos, anonimizarlos o bloquearlos conforme a sus procedimientos internos y obligaciones legales."),
    ]),
    ("14. Seguridad de la información", [
        ("p", "Telvoice.cl implementará medidas técnicas, administrativas y organizativas razonables para proteger los datos personales contra acceso no autorizado, pérdida, destrucción, alteración, uso indebido, divulgación o tratamiento no autorizado."),
        ("p", "Estas medidas pueden incluir:"),
        ("ul", [
            "Control de accesos.",
            "Protección de credenciales.",
            "Uso de conexiones seguras cuando corresponda.",
            "Restricción de acceso a información sensible.",
            "Monitoreo de actividad.",
            "Respaldo de información cuando sea necesario.",
            "Gestión de incidentes.",
            "Protección de claves API y tokens.",
            "Buenas prácticas de seguridad operativa.",
        ]),
        ("p", "No obstante, ningún sistema tecnológico es completamente infalible. El usuario también debe adoptar medidas de seguridad adecuadas, como proteger sus credenciales, limitar accesos internos, resguardar claves API y evitar compartir información sensible por canales inseguros."),
    ]),
    ("15. Derechos de los titulares de datos", [
        ("p", "Los titulares de datos personales podrán ejercer los derechos reconocidos por la normativa aplicable, incluyendo, según corresponda:"),
        ("ul", [
            "Acceder a sus datos personales.",
            "Solicitar rectificación de datos incorrectos o desactualizados.",
            "Solicitar eliminación o cancelación de datos cuando proceda.",
            "Oponerse a determinados tratamientos.",
            "Solicitar bloqueo o limitación del tratamiento cuando corresponda.",
            "Revocar autorizaciones o consentimientos, cuando el tratamiento se base en consentimiento.",
            "Solicitar información sobre el uso, origen, finalidad y destinatarios de sus datos.",
            "Ejercer otros derechos que la normativa vigente o futura reconozca.",
        ]),
        ("html", "Para ejercer estos derechos, el titular podrá escribir a: <a href=\"mailto:legal@telvoice.cl\">legal@telvoice.cl</a>"),
        ("p", "La solicitud deberá incluir información suficiente para identificar al solicitante y describir claramente el derecho que desea ejercer. Telvoice.cl podrá solicitar antecedentes adicionales para verificar la identidad del solicitante y evitar entregas indebidas de información."),
    ]),
    ("16. Solicitudes relacionadas con destinatarios de campañas", [
        ("p", "Si una persona recibe un SMS enviado por un cliente de Telvoice.cl y desea ejercer derechos relacionados con esa comunicación, puede contactar directamente al remitente de la campaña si este se encuentra identificado."),
        ("p", "También podrá escribir a legal@telvoice.cl entregando antecedentes del mensaje recibido, tales como:"),
        ("ul", [
            "Número desde el cual recibió el SMS.",
            "Fecha y hora aproximada.",
            "Contenido del mensaje.",
            "Número telefónico destinatario.",
            "Captura o copia del SMS, si la tiene disponible.",
        ]),
        ("p", "Telvoice.cl evaluará la solicitud y podrá adoptar medidas razonables, incluyendo derivar el requerimiento al cliente responsable de la campaña, revisar el tráfico asociado, bloquear campañas abusivas o aplicar medidas de cumplimiento cuando corresponda."),
    ]),
    ("17. Responsabilidad del usuario sobre datos de terceros", [
        ("p", "El usuario que cargue, integre o utilice datos de terceros en Telvoice.cl declara y garantiza que:"),
        ("ul", [
            "Ha obtenido los datos de forma lícita.",
            "Cuenta con autorización, consentimiento o base legal para tratarlos.",
            "Puede contactar a los destinatarios mediante SMS.",
            "Cumple las obligaciones de información, exclusión y oposición.",
            "No utiliza bases compradas, filtradas, extraídas o recolectadas ilegalmente.",
            "No realiza spam, fraude, suplantación o comunicaciones engañosas.",
            "Mantiene registros suficientes para acreditar la legitimidad de sus campañas.",
        ]),
        ("p", "El usuario será responsable frente a Telvoice.cl, los titulares de datos y las autoridades por cualquier incumplimiento relacionado con el uso de bases de datos o envío de comunicaciones no autorizadas."),
    ]),
    ("18. Menores de edad", [
        ("p", "Telvoice.cl está orientado a empresas, emprendedores, instituciones y usuarios mayores de edad con capacidad para contratar servicios."),
        ("p", "No recopilamos intencionalmente datos personales de menores de edad. Si Telvoice.cl toma conocimiento de que ha recopilado datos de un menor sin autorización válida, podrá eliminarlos o bloquearlos conforme a la normativa aplicable."),
    ]),
    ("19. Enlaces a terceros", [
        ("p", "El sitio Telvoice.cl puede contener enlaces a sitios web, pasarelas de pago, plataformas externas, herramientas de soporte, redes sociales u otros servicios de terceros."),
        ("p", "Telvoice.cl no controla las prácticas de privacidad de dichos terceros y no será responsable por sus contenidos, políticas, medidas de seguridad o tratamiento de datos."),
        ("p", "Se recomienda al usuario revisar las políticas de privacidad de cada sitio o servicio externo que utilice."),
    ]),
    ("20. Cambios en esta Política de Privacidad", [
        ("p", "Telvoice.cl podrá modificar esta Política de Privacidad en cualquier momento para adaptarla a cambios legales, regulatorios, técnicos, comerciales u operativos."),
        ("p", "La versión actualizada será publicada en telvoice.cl con su fecha de actualización. El uso continuado del sitio o de los servicios después de publicada una modificación implicará conocimiento de la nueva versión."),
        ("p", "Cuando los cambios sean sustanciales, Telvoice.cl podrá informar a los usuarios mediante medios razonables, como correo electrónico, aviso en el sitio o comunicación dentro de la plataforma."),
    ]),
    ("21. Relación con los Términos y Condiciones", [
        ("html", "Esta Política de Privacidad forma parte del marco legal de uso de Telvoice.cl y debe leerse junto con los <a href=\"../terminos-y-condiciones/\">Términos y Condiciones</a> del sitio."),
        ("p", "En caso de contradicción entre esta Política de Privacidad y los Términos y Condiciones, prevalecerá la disposición más específica respecto del tratamiento de datos personales."),
    ]),
    ("22. Contacto", [
        ("p", "Para consultas sobre esta Política de Privacidad, tratamiento de datos personales, solicitudes de derechos, reclamos o asuntos de cumplimiento, el usuario puede contactar a Telvoice.cl a través de:"),
        ("contact", [
            ("Correo de contacto", "contacto@telvoice.cl", "mailto:contacto@telvoice.cl"),
            ("Correo legal / cumplimiento", "legal@telvoice.cl", "mailto:legal@telvoice.cl"),
            ("Titular del servicio", "Telefoniachile Ltda", None),
            ("RUT", "76.287.242-0", None),
            ("Domicilio comercial", "Av Caupolicán 222, Temuco, Chile", None),
            ("Sitio web", "telvoice.cl", "https://telvoice.cl/"),
        ]),
    ]),
]
