"""Contenido legal de la Política de Uso Responsable (Telvoice.cl).

Editar SECTIONS y regenerar la página con:

    python3 scripts/build-uso-responsable-page.py
"""

SECTIONS = [
    ("1. Objetivo de esta política", [
        ("p", "La presente Política de Uso Responsable establece las condiciones mínimas que deben cumplir los usuarios, clientes y empresas que utilizan Telvoice.cl para el envío de mensajes SMS, campañas comerciales, notificaciones, alertas, validaciones OTP, recordatorios, comunicaciones transaccionales o integraciones mediante API."),
        ("p", "El objetivo es promover un uso seguro, legítimo, transparente y responsable de los servicios de mensajería SMS, protegiendo a los destinatarios, a los clientes, a la plataforma Telvoice.cl y a la operación general del servicio."),
    ]),
    ("2. Alcance", [
        ("p", "Esta política aplica a todo usuario, empresa, institución, desarrollador, integrador o tercero autorizado que utilice Telvoice.cl para:"),
        ("ul", [
            "Comprar bolsas de SMS.",
            "Enviar campañas SMS.",
            "Utilizar la plataforma de envío.",
            "Integrar servicios mediante API.",
            "Enviar mensajes transaccionales.",
            "Enviar códigos OTP o validaciones.",
            "Realizar comunicaciones comerciales, informativas u operativas.",
            "Gestionar tráfico SMS hacia destinatarios en Chile u otros destinos disponibles.",
        ]),
        ("html", "El uso de Telvoice.cl implica la aceptación de esta Política de Uso Responsable, junto con los <a href=\"../terminos-y-condiciones/\">Términos y Condiciones</a> y la <a href=\"../politica-de-privacidad/\">Política de Privacidad</a> del sitio."),
    ]),
    ("3. Principio general de uso responsable", [
        ("p", "El usuario deberá utilizar Telvoice.cl únicamente para fines lícitos, legítimos y relacionados con su actividad comercial, institucional u operacional."),
        ("p", "Toda campaña, integración o envío SMS debe respetar los siguientes principios:"),
        ("ul", [
            "Legalidad.",
            "Transparencia.",
            "Veracidad.",
            "Seguridad.",
            "Respeto al destinatario.",
            "Protección de datos personales.",
            "Identificación adecuada del remitente.",
            "Uso de bases de datos autorizadas.",
            "Respeto de solicitudes de baja, oposición o no contacto.",
            "Cumplimiento de la normativa aplicable.",
        ]),
        ("p", "Telvoice.cl no debe utilizarse para enviar comunicaciones engañosas, abusivas, fraudulentas, no autorizadas o que puedan afectar la seguridad, privacidad o confianza de los destinatarios."),
    ]),
    ("4. Responsabilidad del usuario", [
        ("p", "El usuario es el único responsable del contenido de los mensajes que envía, de las bases de datos que utiliza, del origen de los números telefónicos, de la finalidad de cada campaña y del cumplimiento de las normas aplicables a sus comunicaciones."),
        ("p", "El usuario declara y garantiza que:"),
        ("ul", [
            "Los destinatarios fueron obtenidos de forma lícita.",
            "Cuenta con autorización, consentimiento o base legal suficiente para contactarlos.",
            "Los mensajes enviados son verdaderos, claros y no inducen a error.",
            "Respeta las solicitudes de baja, exclusión, oposición o no contacto.",
            "No utilizará Telvoice.cl para spam, fraude, phishing, smishing o suplantación de identidad.",
            "Cumplirá las normas de protección de datos, consumidor, telecomunicaciones, publicidad y comercio electrónico que correspondan.",
        ]),
        ("p", "Telvoice.cl actúa como proveedor tecnológico y operativo de mensajería SMS, pero no valida de forma previa la legalidad de cada base de datos utilizada por el cliente, salvo cuando sea necesario realizar revisiones por seguridad, cumplimiento, abuso, reclamos o riesgo operativo."),
    ]),
    ("5. Usos permitidos", [
        ("p", "El servicio puede utilizarse para comunicaciones legítimas, tales como:"),
        ("ul", [
            "Campañas comerciales autorizadas.",
            "Promociones enviadas a bases propias o autorizadas.",
            "Recordatorios de citas o reservas.",
            "Confirmaciones de compra.",
            "Notificaciones de despacho.",
            "Alertas de seguridad.",
            "Mensajes transaccionales.",
            "Códigos OTP o validaciones.",
            "Comunicaciones de cobranza permitidas por la ley.",
            "Información relevante para clientes, usuarios, pacientes, afiliados o miembros de una organización.",
            "Alertas operativas o logísticas.",
            "Mensajes relacionados con servicios contratados por el destinatario.",
        ]),
        ("p", "Cada uso debe estar respaldado por una finalidad legítima y por una base de contacto válida."),
    ]),
    ("6. Usos prohibidos", [
        ("p", "Está estrictamente prohibido utilizar Telvoice.cl para enviar, facilitar o promover mensajes relacionados con:"),
        ("ul", [
            "Spam o comunicaciones no autorizadas.",
            "Phishing, smishing, fraude o suplantación de identidad.",
            "Estafas, engaños o captación ilícita de datos.",
            "Enlaces maliciosos, malware o sitios fraudulentos.",
            "Mensajes falsos, confusos o diseñados para inducir a error.",
            "Promoción de actividades ilegales.",
            "Amenazas, acoso, extorsión o intimidación.",
            "Contenido discriminatorio, violento, abusivo o difamatorio.",
            "Venta no autorizada de productos o servicios regulados.",
            "Juegos de azar no autorizados.",
            "Contenido sexual explícito o servicios para adultos cuando no corresponda legalmente.",
            "Sustancias prohibidas o actividades ilícitas.",
            "Mensajes que vulneren derechos de terceros.",
            "Campañas que oculten la identidad real del remitente.",
            "Uso de bases de datos compradas, filtradas, extraídas o recolectadas sin autorización.",
            "Envíos destinados a evadir bloqueos, filtros, regulaciones o controles de operadores.",
        ]),
        ("p", "Telvoice.cl podrá suspender, bloquear o cancelar cualquier cuenta, campaña, integración, remitente o tráfico que infrinja esta política."),
    ]),
    ("7. Bases de datos y consentimiento", [
        ("p", "El usuario deberá utilizar únicamente bases de datos obtenidas de forma lícita y autorizada."),
        ("p", "No se permite cargar o utilizar bases de datos que provengan de:"),
        ("ul", [
            "Compra de bases sin autorización verificable.",
            "Extracción automatizada de sitios web.",
            "Filtraciones de datos.",
            "Registros obtenidos sin consentimiento o sin base legal.",
            "Listados de origen desconocido.",
            "Bases que incluyan personas que hayan solicitado no ser contactadas.",
        ]),
        ("p", "El usuario debe mantener mecanismos internos que permitan acreditar, cuando corresponda, el origen de sus contactos y la autorización para enviar comunicaciones SMS."),
    ]),
    ("8. Identificación del remitente", [
        ("p", "Todo mensaje enviado debe permitir que el destinatario identifique de forma clara quién envía la comunicación o en nombre de quién se envía."),
        ("p", "Cuando corresponda, el mensaje deberá incluir:"),
        ("ul", [
            "Nombre comercial, marca o entidad responsable.",
            "Finalidad clara de la comunicación.",
            "Información suficiente para que el destinatario entienda por qué recibe el mensaje.",
            "Mecanismo de baja, exclusión u oposición cuando aplique.",
        ]),
        ("p", "No se permite enviar mensajes que simulen provenir de bancos, instituciones, comercios, organismos públicos, operadores móviles u otras entidades sin autorización expresa."),
    ]),
    ("9. Baja, oposición y solicitudes de no contacto", [
        ("p", "El usuario debe respetar toda solicitud de baja, exclusión, oposición o no contacto realizada por un destinatario."),
        ("p", "Cuando se trate de comunicaciones promocionales o publicitarias, el usuario deberá contar con mecanismos razonables para evitar contactar nuevamente a personas que hayan solicitado dejar de recibir mensajes."),
        ("p", "El usuario también deberá considerar las solicitudes ingresadas por consumidores a través de mecanismos oficiales aplicables, como herramientas de exclusión o “No Molestar” cuando corresponda."),
        ("p", "Telvoice.cl podrá solicitar al usuario antecedentes sobre sus mecanismos de baja, listas de exclusión o gestión de solicitudes de no contacto si existen reclamos, riesgos o requerimientos de cumplimiento."),
    ]),
    ("10. Contenido de los mensajes", [
        ("p", "El contenido de cada SMS debe ser claro, veraz y proporcional a la finalidad del envío."),
        ("p", "El usuario debe evitar:"),
        ("ul", [
            "Mensajes engañosos.",
            "Promesas falsas.",
            "Ofertas que no puedan ser cumplidas.",
            "Enlaces que oculten su destino real.",
            "Textos que generen urgencia falsa para obtener datos.",
            "Comunicaciones que aparenten ser oficiales sin serlo.",
            "Uso de marcas, nombres o instituciones sin autorización.",
            "Mensajes que puedan confundirse con alertas bancarias, gubernamentales o de seguridad si no corresponden realmente.",
        ]),
        ("p", "Telvoice.cl podrá bloquear campañas o mensajes cuando detecte contenido riesgoso, fraudulento, abusivo o contrario a esta política."),
    ]),
    ("11. Enlaces dentro de los SMS", [
        ("p", "Cuando un mensaje incluya enlaces, el usuario será responsable de que dichos enlaces dirijan a sitios seguros, legítimos y coherentes con el contenido del SMS."),
        ("p", "No se permiten enlaces hacia:"),
        ("ul", [
            "Sitios fraudulentos.",
            "Formularios de captura de datos sin autorización.",
            "Páginas que suplanten marcas o instituciones.",
            "Sitios con malware.",
            "Redirecciones engañosas.",
            "Contenido prohibido por esta política.",
        ]),
        ("p", "Telvoice.cl podrá solicitar revisión de enlaces o bloquear campañas cuando existan señales de riesgo, reclamos o sospecha de abuso."),
    ]),
    ("12. Uso de API", [
        ("p", "Los usuarios que integren Telvoice.cl mediante API deberán adoptar medidas de seguridad adecuadas para evitar uso indebido, envíos no autorizados o exposición de credenciales."),
        ("p", "El usuario deberá:"),
        ("ul", [
            "Proteger sus claves API, tokens y credenciales.",
            "No compartir accesos con terceros no autorizados.",
            "Implementar controles internos de seguridad.",
            "Validar destinatarios y contenidos antes de enviar.",
            "Evitar envíos duplicados o accidentales.",
            "Respetar límites técnicos y reglas operativas.",
            "Informar a Telvoice.cl cualquier incidente de seguridad.",
        ]),
        ("p", "Telvoice.cl podrá suspender o revocar accesos API si detecta uso indebido, abuso, tráfico irregular, riesgo de fraude, incidentes de seguridad o afectación de la estabilidad del servicio."),
    ]),
    ("13. Tráfico OTP y mensajes transaccionales", [
        ("p", "Los mensajes OTP, códigos de validación, alertas de seguridad y mensajes transaccionales deben utilizarse exclusivamente para finalidades legítimas de autenticación, confirmación, seguridad o información relacionada con una acción real del usuario final."),
        ("p", "No se permite utilizar mensajes transaccionales para ocultar campañas promocionales, evadir reglas comerciales o contactar destinatarios sin autorización."),
        ("p", "El usuario será responsable de asegurar que cada OTP, alerta o mensaje transaccional corresponda a una solicitud, relación o evento válido."),
    ]),
    ("14. Prevención de fraude y abuso", [
        ("p", "Telvoice.cl podrá monitorear patrones de uso, volumen, contenido, frecuencia, reclamos, enlaces, tasas de error, rutas, destinatarios y otros elementos técnicos para prevenir fraude, abuso o afectación de la plataforma."),
        ("p", "Entre las medidas que Telvoice.cl podrá adoptar se incluyen:"),
        ("ul", [
            "Solicitar antecedentes adicionales al usuario.",
            "Revisar contenido de campañas.",
            "Limitar temporalmente el envío.",
            "Bloquear campañas específicas.",
            "Suspender accesos API.",
            "Retener tráfico sospechoso.",
            "Cancelar cuentas en caso de infracción grave.",
            "Informar a autoridades competentes cuando corresponda.",
        ]),
        ("p", "Estas medidas podrán aplicarse sin aviso previo cuando exista riesgo de fraude, afectación del servicio, incumplimiento legal, reclamos relevantes o amenaza a la seguridad."),
    ]),
    ("15. Límites operativos y calidad del servicio", [
        ("p", "Telvoice.cl podrá aplicar límites técnicos, comerciales u operativos para proteger la estabilidad del servicio, la reputación de las rutas y la calidad de la mensajería."),
        ("p", "Estos límites pueden estar relacionados con:"),
        ("ul", [
            "Volumen de mensajes.",
            "Velocidad de envío.",
            "Destinos permitidos.",
            "Tipo de campaña.",
            "Horarios de envío.",
            "Contenido.",
            "Uso de API.",
            "Historial del usuario.",
            "Nivel de riesgo del tráfico.",
            "Requerimientos de operadores o proveedores.",
        ]),
        ("p", "Telvoice.cl podrá ajustar estas condiciones cuando sea necesario para mantener una operación segura y estable."),
    ]),
    ("16. Reclamos de destinatarios", [
        ("p", "Si Telvoice.cl recibe reclamos de destinatarios, operadores, autoridades, proveedores o terceros relacionados con campañas enviadas por un usuario, podrá revisar la cuenta, la campaña, el contenido, la base de datos y los antecedentes disponibles."),
        ("p", "El usuario deberá colaborar con Telvoice.cl entregando información razonable para aclarar el origen del tráfico, la autorización de contacto y la finalidad de la campaña."),
        ("p", "Cuando existan reclamos reiterados, señales de abuso o incumplimiento, Telvoice.cl podrá suspender el servicio sin perjuicio de otras acciones disponibles."),
    ]),
    ("17. Suspensión del servicio", [
        ("p", "Telvoice.cl podrá suspender, bloquear o terminar total o parcialmente el servicio si el usuario:"),
        ("ul", [
            "Incumple esta Política de Uso Responsable.",
            "Envía spam o comunicaciones no autorizadas.",
            "Utiliza bases de datos ilegales o no verificables.",
            "Envía contenido fraudulento o engañoso.",
            "Genera reclamos reiterados.",
            "Afecta la reputación de rutas u operadores.",
            "Compromete la seguridad de la plataforma.",
            "Usa API de forma abusiva o insegura.",
            "Incumple obligaciones legales o contractuales.",
            "Se niega a entregar antecedentes razonables de cumplimiento.",
        ]),
        ("p", "La suspensión podrá aplicarse de forma inmediata cuando exista riesgo legal, técnico, reputacional, comercial o de seguridad."),
    ]),
    ("18. Cooperación con autoridades", [
        ("p", "Telvoice.cl podrá colaborar con autoridades competentes, operadores, proveedores tecnológicos o entidades reguladoras cuando exista una obligación legal, requerimiento formal, investigación de fraude, denuncia, incidente de seguridad o incumplimiento grave."),
        ("p", "Dicha colaboración se realizará conforme a la normativa aplicable y a los procedimientos internos de Telvoice.cl."),
    ]),
    ("19. Reporte de abuso", [
        ("p", "Cualquier persona que reciba un SMS que considere fraudulento, engañoso, no autorizado o abusivo puede reportarlo a Telvoice.cl escribiendo a:"),
        ("html", "<a href=\"mailto:legal@telvoice.cl\">legal@telvoice.cl</a>"),
        ("p", "El reporte idealmente debe incluir:"),
        ("ul", [
            "Número que recibió el mensaje.",
            "Fecha y hora aproximada.",
            "Contenido del SMS.",
            "Captura de pantalla, si está disponible.",
            "Nombre de la empresa o marca mencionada.",
            "Enlace incluido en el mensaje, si corresponde.",
        ]),
        ("p", "Telvoice.cl revisará los antecedentes y podrá adoptar medidas razonables según la información disponible."),
    ]),
    ("20. Relación con otros documentos legales", [
        ("html", "Esta Política de Uso Responsable complementa los <a href=\"../terminos-y-condiciones/\">Términos y Condiciones</a> y la <a href=\"../politica-de-privacidad/\">Política de Privacidad</a> de Telvoice.cl."),
        ("p", "En caso de conflicto entre esta política y otros documentos legales del sitio, prevalecerá la disposición más específica respecto del uso aceptable, prevención de abuso, seguridad o cumplimiento normativo del servicio SMS."),
    ]),
    ("21. Modificaciones", [
        ("p", "Telvoice.cl podrá modificar esta Política de Uso Responsable en cualquier momento para adaptarla a cambios legales, regulatorios, técnicos, comerciales u operativos."),
        ("p", "La versión actualizada será publicada en telvoice.cl con su fecha de actualización. El uso continuado del servicio después de publicada una modificación implicará conocimiento y aceptación de la nueva versión."),
    ]),
    ("22. Contacto", [
        ("p", "Para consultas relacionadas con esta Política de Uso Responsable, reportes de abuso, cumplimiento o uso del servicio, puedes contactar a Telvoice.cl a través de:"),
        ("contact", [
            ("Correo de contacto", "contacto@telvoice.cl", "mailto:contacto@telvoice.cl"),
            ("Correo legal / cumplimiento", "legal@telvoice.cl", "mailto:legal@telvoice.cl"),
            ("Titular del servicio", "Telefoniachile Ltda", None),
            ("RUT", "76.287.242-0", None),
            ("Domicilio comercial", "Av Caupolicán 222, Temuco, Chile", None),
            ("Sitio web", "telvoice.cl", "https://telvoice.cl/"),
        ]),
    ]),
]
