export const MOCK_REPORT_ROWS = [
  {
    id: "r1",
    date: "22 may 2026",
    campaign: "OTP Verificación",
    recipients: 1200,
    sent: 1200,
    delivered: 1188,
    failed: 8,
    pending: 4,
    operator: "Entel",
    cost: "$84.000",
    rate: 99.0,
    perf: "excelente" as const,
  },
  {
    id: "r2",
    date: "21 may 2026",
    campaign: "Retail Mayo",
    recipients: 2400,
    sent: 2395,
    delivered: 2280,
    failed: 95,
    pending: 20,
    operator: "Movistar",
    cost: "$168.000",
    rate: 95.2,
    perf: "normal" as const,
  },
  {
    id: "r3",
    date: "20 may 2026",
    campaign: "Recordatorio pago",
    recipients: 890,
    sent: 890,
    delivered: 810,
    failed: 62,
    pending: 18,
    operator: "WOM",
    cost: "$62.300",
    rate: 91.0,
    perf: "bajo" as const,
  },
  {
    id: "r4",
    date: "19 may 2026",
    campaign: "Logística despacho",
    recipients: 450,
    sent: 450,
    delivered: 380,
    failed: 58,
    pending: 12,
    operator: "Claro",
    cost: "$31.500",
    rate: 84.4,
    perf: "revisar" as const,
  },
];

export const MOCK_CONTACTS = [
  {
    id: "c1",
    name: "María González",
    phone: "+56 9 8765 4321",
    company: "Retail Andes",
    email: "maria@retailandes.cl",
    list: "Clientes activos",
    tags: "VIP, Retail",
    status: "activo",
    lastSms: "22 may · OTP",
  },
  {
    id: "c2",
    name: "Carlos Pérez",
    phone: "+56 9 1234 5678",
    company: "Finanzas Sur",
    email: "cperez@finanzasur.cl",
    list: "Cobranza",
    tags: "Cobranza",
    status: "activo",
    lastSms: "21 may · Recordatorio",
  },
  {
    id: "c3",
    name: "Ana Ruiz",
    phone: "+56 9 5555 0101",
    company: "—",
    email: "—",
    list: "Leads",
    tags: "Lead",
    status: "sin_validar",
    lastSms: "—",
  },
  {
    id: "c4",
    name: "Duplicado test",
    phone: "+56 9 8765 4321",
    company: "Otra empresa",
    email: "dup@test.cl",
    list: "Promociones",
    tags: "—",
    status: "duplicado",
    lastSms: "—",
  },
  {
    id: "c5",
    name: "Usuario opt-out",
    phone: "+56 9 7777 8888",
    company: "—",
    email: "—",
    list: "—",
    tags: "—",
    status: "optout",
    lastSms: "20 may · STOP",
  },
];

export const MOCK_CONTACT_LISTS = [
  {
    id: "cl-active",
    name: "Clientes activos",
    label: "Clientes activos CL",
    count: 2400,
    updated: "22 may 2026",
    sampleNumbers: ["56911111111", "56912222222", "56913333333"],
  },
  {
    id: "leads-30d",
    name: "Leads",
    label: "Leads últimos 30 días",
    count: 890,
    updated: "21 may 2026",
    sampleNumbers: ["56914444444", "56915555555"],
  },
  {
    id: "cobranza",
    name: "Cobranza",
    label: "Cobranza",
    count: 620,
    updated: "20 may 2026",
    sampleNumbers: ["56916666666", "56917777777"],
  },
  {
    id: "recordatorios",
    name: "Recordatorios",
    label: "Recordatorios",
    count: 1100,
    updated: "19 may 2026",
    sampleNumbers: ["56918888888", "56919999999"],
  },
  {
    id: "promo",
    name: "Promociones",
    label: "Promociones",
    count: 3500,
    updated: "18 may 2026",
    sampleNumbers: ["56910101010", "56912121212"],
  },
  {
    id: "otp",
    name: "Validaciones OTP",
    label: "Validaciones OTP",
    count: 450,
    updated: "22 may 2026",
    sampleNumbers: ["56913131313"],
  },
  {
    id: "soporte",
    name: "Soporte",
    label: "Soporte",
    count: 120,
    updated: "17 may 2026",
    sampleNumbers: ["56914141414"],
  },
];

export const MOCK_INVOICES = [
  {
    id: "inv1",
    date: "15 may 2026",
    doc: "FAC-2026-0842",
    type: "Factura",
    bag: "10.000 SMS CL",
    net: "$84.034",
    iva: "$15.966",
    total: "$100.000",
    status: "pagada",
    payment: "MercadoPago",
  },
  {
    id: "inv2",
    date: "02 may 2026",
    doc: "FAC-2026-0791",
    type: "Factura",
    bag: "50.000 SMS CL",
    net: "$378.151",
    iva: "$71.849",
    total: "$450.000",
    status: "pagada",
    payment: "Transferencia",
  },
  {
    id: "inv3",
    date: "28 abr 2026",
    doc: "COT-2026-1201",
    type: "Cotización",
    bag: "100.000 SMS CL",
    net: "—",
    iva: "—",
    total: "$820.000 est.",
    status: "en_revision",
    payment: "—",
  },
  {
    id: "inv4",
    date: "10 abr 2026",
    doc: "FAC-2026-0710",
    type: "Factura",
    bag: "10.000 SMS CL",
    net: "$84.034",
    iva: "$15.966",
    total: "$100.000",
    status: "vencida",
    payment: "Pendiente",
  },
];

export const MOCK_SMS_BAGS = [
  { name: "Bolsa Chile 10.000 SMS", bought: "15 may 2026", used: 4200, available: 5800, status: "activa" },
  { name: "Bolsa Chile 50.000 SMS", bought: "02 may 2026", used: 38500, available: 11500, status: "activa" },
  { name: "Bolsa Chile 100.000 SMS", bought: "—", used: 0, available: 0, status: "cotización" },
];

export const MOCK_TEMPLATES = [
  {
    id: "t1",
    name: "Código OTP",
    category: "OTP / Validación",
    message:
      "Tu código de verificación {empresa} es {codigo}. No lo compartas con nadie.",
    vars: "{empresa}, {codigo}",
    lastUse: "Hoy",
    status: "activa",
  },
  {
    id: "t2",
    name: "Recordatorio de cita",
    category: "Recordatorios",
    message:
      "Hola {nombre}, te recordamos tu cita para el día {fecha}. Responde SI para confirmar.",
    vars: "{nombre}, {fecha}",
    lastUse: "Ayer",
    status: "activa",
  },
  {
    id: "t3",
    name: "Confirmación de compra",
    category: "Retail",
    message: "Gracias por tu compra en {empresa}. Tu pedido fue confirmado correctamente.",
    vars: "{empresa}",
    lastUse: "20 may",
    status: "activa",
  },
  {
    id: "t4",
    name: "Cobranza amigable",
    category: "Cobranzas",
    message:
      "Hola {nombre}, tienes un pago pendiente por {monto}. Regulariza tu cuenta con {empresa}.",
    vars: "{nombre}, {monto}, {empresa}",
    lastUse: "18 may",
    status: "activa",
  },
  {
    id: "t5",
    name: "Despacho en camino",
    category: "Despacho / logística",
    message:
      "Tu pedido de {empresa} va en camino. Te notificaremos cuando sea entregado.",
    vars: "{empresa}",
    lastUse: "15 may",
    status: "activa",
  },
];

export const MOCK_CHAT_TICKETS = [
  {
    id: "tk1",
    subject: "Activación API",
    status: "en_revision",
    priority: "alta",
    updated: "Hace 12 min",
    area: "Técnico",
  },
  {
    id: "tk2",
    subject: "Duda sobre factura FAC-0842",
    status: "abierto",
    priority: "media",
    updated: "Hace 2 h",
    area: "Comercial",
  },
  {
    id: "tk3",
    subject: "Error en campaña Retail Mayo",
    status: "abierto",
    priority: "critica",
    updated: "Hace 4 h",
    area: "Operaciones",
  },
  {
    id: "tk4",
    subject: "Solicitud alto volumen",
    status: "resuelto",
    priority: "alta",
    updated: "Ayer",
    area: "Comercial",
  },
  {
    id: "tk5",
    subject: "Revisión de saldo",
    status: "cerrado",
    priority: "baja",
    updated: "18 may",
    area: "Soporte",
  },
];
